apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd   # ArgoCD runs here
spec:
  project: default

  source:
    repoURL: https://github.com/007-bg/kind-config.git
    targetRevision: main
    path: k8s          # folder where manifests are stored

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
